<p class="h2">Articles</p>
<hr>

<div class="row justify-content-between mb-5 mx-auto">
    <a href="<?= INDEX."?page=admin_users"?>" class="col-2 btn btn-primary btn-lg" role="button" aria-pressed="true">Users</a>
</div>

<div class="table-wrapper">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Date</th>

            <th>Reviewers</th>
            <th>Originality</th>
            <th>Format</th>
            <th>Language</th>
            <th>Total</th>
            <th></th>
        </tr>
        </thead>

        <tbody>

        <?php foreach ($data as $contribution): ?>
            <?php if (!is_array($contribution)) break; ?>
            <?php if (!isset($contribution["reviews"])) continue; ?>

            <tr>
                <td rowspan="3"><a href="<?= ROOT_PATH.FILES.$contribution["attributes"]["file"]; ?>" target="_blank"><?= $contribution["attributes"]["title"]; ?></a></td>
                <td rowspan="3"><?= $contribution["attributes"]["author"]; ?></td>
                <td rowspan="3"><?= $contribution["attributes"]["date"]; ?></td>

                <!-- Reviewer 1 -->
                <?php if ($contribution["reviews"]["rev1"]["username"] == null): ?>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                Dropdown
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Link 1</a>
                                <a class="dropdown-item" href="#">Link 2</a>
                                <a class="dropdown-item" href="#">Link 3</a>
                            </div>
                        </div>
                    </td>

                    <td colspan="3">
                        <form action="<?= INDEX ?>" method="post">
                            <button type="submit" name="assign_review" value="1" class="btn btn-outline-primary btn-block">Assign</button>
                        </form>
                    </td>

                <?php else: ?>
                    <td><span title="<?= $contribution["reviews"]["rev1"]["comment"] ?>"><?= $contribution["reviews"]["rev1"]["username"] ?></span></td>
                    <td><?= $contribution["reviews"]["rev1"]["originality"] ?></td>
                    <td><?= $contribution["reviews"]["rev1"]["format"] ?></td>
                    <td><?= $contribution["reviews"]["rev1"]["language"] ?></td>

                <?php endif; ?>

                <td rowspan="3">
                    <div>
                        <form action="<?= INDEX ?>" method="post">
                            <button type="submit" name="accept_article" value="<?= $contribution["attributes"]["id_article"] ?>" class="btn btn-success">Accept</button>
                            <button type="submit" name="refuse_article" value="<?= $contribution["attributes"]["id_article"] ?>" class="btn btn-danger">Refuse</button>
                        </form>
                        <span><?php
                            switch ($contribution["attributes"]["status"]) {
                                case "accepted":
                                    echo "accepted";
                                    break;
                                case "refused":
                                    echo "refused";
                                    break;
                                default:
                                    echo "";
                            }
                            ?></span>
                    </div>
                </td>
            </tr>

            <tr>
                <!-- Reviewer 2 -->
                <?php if ($contribution["reviews"]["rev2"]["username"] == null): ?>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                Dropdown
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Link 1</a>
                                <a class="dropdown-item" href="#">Link 2</a>
                                <a class="dropdown-item" href="#">Link 3</a>
                            </div>
                        </div>
                    </td>

                    <td colspan="3">
                        <form action="<?= INDEX ?>" method="post">
                            <button type="submit" name="assign_review" value="2" class="btn btn-outline-primary btn-block">Assign</button>
                        </form>
                    </td>

                <?php else: ?>
                    <td><span title="<?= $contribution["reviews"]["rev2"]["comment"] ?>"><?= $contribution["reviews"]["rev2"]["username"] ?></span></td>
                    <td><?= $contribution["reviews"]["rev2"]["originality"] ?></td>
                    <td><?= $contribution["reviews"]["rev2"]["format"] ?></td>
                    <td><?= $contribution["reviews"]["rev2"]["language"] ?></td>

                <?php endif; ?>
            </tr>

            <tr>
                <!-- Reviewer 3 -->
                <?php if ($contribution["reviews"]["rev3"]["username"] == null): ?>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                Dropdown
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Link 1</a>
                                <a class="dropdown-item" href="#">Link 2</a>
                                <a class="dropdown-item" href="#">Link 3</a>
                            </div>
                        </div>
                    </td>

                    <td colspan="3">
                        <form action="<?= INDEX ?>" method="post">
                            <button type="submit" name="assign_review" value="3" class="btn btn-outline-primary btn-block">Assign</button>
                        </form>
                    </td>

                <?php else: ?>
                    <td><span title="<?= $contribution["reviews"]["rev3"]["comment"] ?>"><?= $contribution["reviews"]["rev3"]["username"] ?></span></td>
                    <td><?= $contribution["reviews"]["rev3"]["originality"] ?></td>
                    <td><?= $contribution["reviews"]["rev3"]["format"] ?></td>
                    <td><?= $contribution["reviews"]["rev3"]["language"] ?></td>

                <?php endif; ?>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>

    <div class="row justify-content-between mb-5 mx-auto">
        <a href="<?= INDEX."?page=admin_users"?>" class="col-2 btn btn-primary btn-lg" role="button" aria-pressed="true">Users</a>
        <p class="col-4 h5">Last login: <span class="h6"><?= $data["last_login"] ?></span></p>
    </div>
</div>
