<p class="h2">Articles</p>
<hr>

<div class="row justify-content-between mb-5 mx-auto">
    <a href="<?= INDEX."?page=user&sub_page=admin_users"?>" class="col-2 btn btn-primary btn-lg" role="button" aria-pressed="true">Users</a>
</div>

<div class="table-wrapper">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Date</th>

            <th>Reviewers</th>
            <th>Originality</th>
            <th>Format</th>
            <th>Language</th>
            <th></th>
        </tr>
        </thead>

        <tbody>

        <?php foreach ($data as $key => $contribution): ?>
            <?php if (!is_array($contribution)) break; ?>
            <?php if (!isset($contribution["reviews"])) continue; ?>

            <tr>
                <!-- begin columns -->
                <td rowspan="3"><a href="<?= ROOT_PATH.FILES.$contribution["attributes"]["file"]; ?>" target="_blank"><?= $contribution["attributes"]["title"]; ?></a></td>
                <td rowspan="3"><?= $contribution["attributes"]["author"]; ?></td>
                <td rowspan="3"><?= $contribution["attributes"]["date"]; ?></td>

                <!-- Reviewer 1 -->
                <?php if ($contribution["reviews"]["rev1"]["username"] == null): ?>
                    <td>
                        <select id="<?= 'select_rev1'.$key ?>" class="custom-select btn">
                            <?php foreach ($data["all_revs"] as $reviewer): ?>
                                <?php if (!in_array($reviewer["username"], array(
                                    $contribution["reviews"]["rev1"]["username"],
                                    $contribution["reviews"]["rev2"]["username"],
                                    $contribution["reviews"]["rev3"]["username"]
                                ))): ?>
                                    <option value="<?= $reviewer["id_user"]; ?>"><?= $reviewer["username"]; ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                    </td>

                    <td colspan="3">
                        <form action="<?= INDEX ?>" method="post">
                            <input type="hidden" name="assign_review_on" value="<?= $contribution["attributes"]["id_article"] ?>" />
                            <button id="<?= 'submit_rev1'.$key ?>" type="submit" name="assign_review_to" onclick="setReviewerValue(1, '<?= $key ?>')" class="btn btn-outline-primary btn-block">Assign</button>
                        </form>
                    </td>

                <!-- end columns -->
                <?php else: ?>
                    <td><span title="<?= $contribution["reviews"]["rev1"]["comment"] ?>"><?= $contribution["reviews"]["rev1"]["username"] ?></span></td>
                    <td><?= $contribution["reviews"]["rev1"]["originality"] ?></td>
                    <td><?= $contribution["reviews"]["rev1"]["format"] ?></td>
                    <td><?= $contribution["reviews"]["rev1"]["language"] ?></td>

                <?php endif; ?>

                <td rowspan="3">
                    <div>
                        <form action="<?= INDEX ?>" method="post">
                            <button type="submit" name="publish_article" value="<?= $contribution["attributes"]["id_article"] ?>" class="btn btn-success">Publish</button>
                            <button type="submit" name="refuse_article" value="<?= $contribution["attributes"]["id_article"] ?>" class="btn btn-danger">Refuse</button>
                        </form>
                        <span><?php echo $contribution["attributes"]["status"] != "reviewing" ? $contribution["attributes"]["status"] : ""; ?></span>
                    </div>
                </td>
            </tr>

            <tr>
                <!-- Reviewer 2 -->
                <?php if ($contribution["reviews"]["rev2"]["username"] == null): ?>
                    <td>
                        <select id="<?= 'select_rev2'.$key ?>" class="custom-select btn">
                            <?php foreach ($data["all_revs"] as $reviewer): ?>
                                <?php if (!in_array($reviewer["username"], array(
                                    $contribution["reviews"]["rev1"]["username"],
                                    $contribution["reviews"]["rev2"]["username"],
                                    $contribution["reviews"]["rev3"]["username"]
                                ))): ?>
                                    <option value="<?= $reviewer["id_user"]; ?>"><?= $reviewer["username"]; ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                    </td>

                    <td colspan="3">
                        <form action="<?= INDEX ?>" method="post">
                            <input type="hidden" name="assign_review_on" value="<?= $contribution["attributes"]["id_article"] ?>" />
                            <button id="<?= 'submit_rev2'.$key ?>" type="submit" name="assign_review_to" onclick="setReviewerValue(2, '<?= $key ?>')" class="btn btn-outline-primary btn-block">Assign</button>
                        </form>
                    </td>

                <!-- end columns -->
                <?php else: ?>
                    <td><span title="<?= $contribution["reviews"]["rev2"]["comment"] ?>"><?= $contribution["reviews"]["rev2"]["username"] ?></span></td>
                    <td><?= $contribution["reviews"]["rev2"]["originality"] ?></td>
                    <td><?= $contribution["reviews"]["rev2"]["format"] ?></td>
                    <td><?= $contribution["reviews"]["rev2"]["language"] ?></td>

                <?php endif; ?>
            </tr>

            <tr>
                <!-- Reviewer 3 -->
                <?php if ($contribution["reviews"]["rev3"]["username"] == null): ?>
                    <td>
                        <select id="<?= 'select_rev3'.$key ?>" class="custom-select btn">
                            <?php foreach ($data["all_revs"] as $reviewer): ?>
                                <?php if (!in_array($reviewer["username"], array(
                                    $contribution["reviews"]["rev1"]["username"],
                                    $contribution["reviews"]["rev2"]["username"],
                                    $contribution["reviews"]["rev3"]["username"]
                                ))): ?>
                                    <option value="<?= $reviewer["id_user"]; ?>"><?= $reviewer["username"]; ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                    </td>

                    <td colspan="3">
                        <form action="<?= INDEX ?>" method="post">
                            <input type="hidden" name="assign_review_on" value="<?= $contribution["attributes"]["id_article"] ?>" />
                            <button id="<?= 'submit_rev3'.$key ?>" type="submit" name="assign_review_to" onclick="setReviewerValue(3, '<?= $key ?>')" class="btn btn-outline-primary btn-block">Assign</button>
                        </form>
                    </td>

                <!-- end columns -->
                <?php else: ?>
                    <td><span title="<?= $contribution["reviews"]["rev3"]["comment"] ?>"><?= $contribution["reviews"]["rev3"]["username"] ?></span></td>
                    <td><?= $contribution["reviews"]["rev3"]["originality"] ?></td>
                    <td><?= $contribution["reviews"]["rev3"]["format"] ?></td>
                    <td><?= $contribution["reviews"]["rev3"]["language"] ?></td>

                <?php endif; ?>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>

    <div class="row justify-content-between mb-5 mx-auto">
        <a href="<?= INDEX."?page=user&sub_page=admin_users"?>" class="col-2 btn btn-primary btn-lg" role="button" aria-pressed="true">Users</a>
        <p class="col-4 h5">Last login: <span class="h6"><?= $data["last_login"] ?></span></p>
    </div>
</div>

<script>
    function setReviewerValue(id_rev, key) {
        document.getElementById("submit_rev" + id_rev + key).value = document.getElementById("select_rev" + id_rev + key).value;
    }
</script>