<p class="h2">My articles</p>
<hr>

<div class="table-wrapper">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr class="row mx-auto">
            <th class="col-3">Title</th>
            <th class="col-2">Date</th>
            <th class="col-3">File</th>
            <th class="col-1">State</th>
            <th class="col-1">Rating</th>
            <th class="col-2"></th>
        </tr>
        </thead>

        <tbody>

        <?php foreach ($data as $key => $article): ?>
            <?php if (!is_array($article)) break; ?>

        <tr class="row mx-auto">
            <td class="col-3"><?= $article["title"]; ?></td>
            <td class="col-2"><?= $article["date"]; ?></td>
            <td class="col-3"><a href="<?= ROOT_PATH.FILES.$article["file"]; ?>" target="_blank"><?= $article["file"]; ?></a></td>
            <td class="col-1"><?= $article["status"]; ?></td>
            <td class="col-1"><?= $article["rating"] != null ? $article["rating"] : "N/A"; ?></td>
            <td class="col-2">
                <div class="row justify-content-center">
                    <a href="<?= INDEX."?page=new_article&id_article=".$article["id_article"] ?>" class="col-6 btn btn-primary mr-2" role="button" aria-pressed="true">Edit</a>

                    <form action="<?= INDEX ?>" method="post">
                        <button type="submit" name="delete_article" value="<?= $article["id_article"] ?>" class="col btn btn-danger">Delete</button>
                    </form>
                </div>
            </td>
        </tr>

        <?php endforeach; ?>

        </tbody>
    </table>

    <div class="row justify-content-between mb-5 mx-auto">
        <a href="<?= INDEX."?page=new_article"?>" class="col-2 btn btn-primary btn-lg" role="button" aria-pressed="true">New article</a>
        <p class="col-4 h5">Last login: <span class="h6"><?= $data["last_login"] ?></span></p>
    </div>
</div>
