<p class="h2">My articles</p>
<hr>

<div class="table-wrapper">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>Title</th>
            <th>Date</th>
            <th>File</th>
            <th>State</th>
            <th>Rating</th>
            <th></th>
        </tr>
        </thead>

        <tbody>

        <?php foreach ($data as $article): ?>

        <tr>
            <td><?= $article["title"]; ?></td>
            <td><?= $article["date"]; ?></td>
            <td><?= $article["file"]; ?></td>
            <td><?= $article["status"]; ?></td>
            <td><?= $article["rating"] != null ? $article["rating"] : "N/A"; ?></td>
            <td>
                <div class="row justify-content-md-center">
                    <a href="<?= INDEX."?page=new_article?edit=true?id_article=".$article["id_article"] ?>" class="col-6 btn btn-primary mr-2" role="button" aria-pressed="true">Edit</a>

                    <form action="<?= INDEX ?>" method="post">
                        <button type="submit" name="submit_article" value="<?= $article["id_article"] ?>" class="col btn btn-danger">Delete</button>
                    </form>
                </div>
            </td>
        </tr>

        <?php endforeach; ?>

        </tbody>
    </table>

    <div>
        <a href="<?= INDEX."?page=new_article"?>" class="btn btn-primary btn-lg mb-5" role="button" aria-pressed="true">New article</a>
    </div>
</div>
