<div>
    <p class="h1">KIV/WEB conference</p>
    <hr>
    <p class="h4">This year's topic:</p>
    <p class="h2 text-primary">Living standard on Faroe Islands.</p>

    <div class="container row">
        <div class="col">
            <p>
                The Faroe Islands is a North Atlantic archipelago located 320 kilometres north-northwest of Scotland, and about halfway between Norway and Iceland.
                It is an autonomous territory within the Kingdom of Denmark. The islands have a total area of about 1,400 square kilometres with a population of 51 783 as of June 2019.
            </p>
            <p>
                The terrain is rugged; the climate is subpolar oceanic climate windy, wet, cloudy, and cool. Temperatures average above freezing throughout the year because of the Gulf Stream. As a result of the moderation and the northerly latitude, summers normally hover around 12 °C. Average temperatures are 5 °C in winter. The northerly latitude also results in perpetual civil twilight during summer nights and very short winter days.
            </p>
            <p>
                The Faroese control most of their domestic affairs. Those that remain the responsibility of Denmark include military defence, policing and the justice department, currency, and foreign affairs. However, as they are not part of the same customs area as Denmark, the Faroe Islands have an independent trade policy and can establish trade agreements with other states. The islands also have representation in the Nordic Council as members of the Danish delegation. The Faroe Islands have their own national teams competing in certain sports.
            </p>
        </div>
        <div class="col">
            <!-- Embedded Google Map -->
            <iframe width="100%" height="400px" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=62,-7&amp;spn=10,10&amp;t=m&amp;output=embed"></iframe>
        </div>
    </div>
</div>
