<?php
// yes, this template creates a service, which creates a service, which starts session...
$login = new LoginService();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title><?= $title ?></title>

    <!--    <base href="localhost" />-->
    <base href="../../" />

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- own CSS -->
    <style>
        /* padding for navbar */
        body { padding-top: 80px; }
    </style>
</head>

<body>

<!----------------->
<!--  navigation -->
<!----------------->

<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark text-primary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse align-content-around" id="navbarResponsive">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <p class="h2">KIV/WEB conference</p>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link h5" href=<?= INDEX."?page=home"?>>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link h5" href=<?= INDEX."?page=articles"?>>Articles</a>
                    </li>

                    <?php
                    // show user name if user is logged in
                    if ($login->isUserLoged()) {
                        echo "<li class='nav-item'><a class='nav-link h5' href='".INDEX."?page=user'>";
                        echo $login->getUserInfo()[0];
                        echo "</a></li>";
                    }
                    ?>

                </ul>
                <ul class="navbar-nav ml-5">
                    <li>
                        <div class="btn-group row float-right" role="group" aria-label="Basic example">

                            <?php
                            // buttons only for redirect
                            if (!$login->isUserLoged()) { ?>
                                <a href="<?= INDEX."?page=login"?>" class="btn btn-primary" role="button" aria-pressed="true">Log in</a>
                                <a href="<?= INDEX."?page=register"?>" class="btn btn-outline-primary" role="button" aria-pressed="true">Register</a>
                            <?php }
                            else {
                            // button for server post notification about log out
                            ?>
                                <form action="<?= INDEX ?>" method="post" class="m-0">
                                    <button type="submit" name="submit_login" value="logout" class="btn btn-primary">Log out</button>
                                </form>
                            <?php } ?>

                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!----------------------->
<!-- main part of page -->
<!----------------------->

<main>
    <div class="container application-main">
        <?= $this->getContent($view, $data); ?>
    </div>
</main>

<!--------------------->
<!--  footer of page -->
<!--------------------->

<footer class="footer bg-dark

    <?php
        // this makes footer stick on bottom of pages, that are not larger than one screen
        if (in_array($view, array("LoginView", "RegisterView", "err404View", "GoodLuckView")))
        echo "fixed-bottom";
    ?>">

    <div class="container-fluid row m-0 justify-content-between">
        <div class="col">
            <ul class="navbar-nav">
                <li>
                    <span class="h4 text-left text-primary">Contact</span>
                </li>
                <li>
                    <span class="text-primary ml-3">email: </span>
                    <span class="text-white ml-1">matejka.jk@gmail.com</span>
                </li>
                <li>
                    <span class="text-primary ml-3">github: </span>
                    <a class="text-white ml-1" href="https://github.com/matenestor">github.com/matenestor</a>
                </li>
            </ul>
        </div>
        <div class="col">
            <p class="text-white text-right mt-xl-5 mb-0">Copyright © 2019 Jakub Matějka</p>
        </div>
    </div>
</footer>

<!------------->
<!-- Scripts -->
<!------------->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>
