<div class="login-form w-50 ml-auto mr-auto">
    <form method="post">
        <h2 class="text-center">Log in</h2>
        <div class="form-group">
            <input name="username" type="text" class="form-control" placeholder="Username" required="required">
        </div>
        <div class="form-group">
            <input name="password" type="password" class="form-control" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <button name="submit_login" value="login" type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
        <div class="clearfix">
            <a href="<?= INDEX."?page=goodluck"?>" class="pull-right">Forgot Password?</a>
        </div>
    </form>
    <p class="text-center"><a href="<?= INDEX."?page=register"?>">Create an Account</a></p>
</div>
