<div class="signup-form w-50 ml-auto mr-auto">
    <form method="post">
        <h2>Register</h2>
        <p class="hint-text" data-toggle="tooltip" data-placement="down" title="It costs only your soul.">Create your account.</p>
        <div class="form-group">
            <input type="text" name="username" class="form-control" placeholder="User name" required="required">
        </div>
        <div class="form-group">
            <div class="row ml-auto">
                <div class="col-xs-6"><input type="text" name="first_name" class="form-control" placeholder="First name" required="required"></div>
                <div class="col-xs-6"><input type="text" name="last_name" class="form-control" placeholder="Last name" required="required"></div>
            </div>
        </div>
        <div class="form-group">
            <input type="password" name="password" id="pswd1" class="form-control" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <p class="h5">Register as:</p>
            <label class="checkbox-inline"><input type="radio" name="role" value="author" required="required"> Author</label>
            <label class="checkbox-inline"><input type="radio" name="role" value="reviewer" required="required"> Reviewer</label>
        </div>
        <div class="form-group">
            <button type="submit" name="submit_register" value="register" class="btn btn-primary btn-lg btn-block">Register Now</button>
        </div>
    </form>
    <div class="text-center">Already have an account? <a href="<?= INDEX."?page=login"?>">Log in</a></div>
</div>