<p class="h2">Reviews</p>
<hr>

<div class="table-wrapper table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Date</th>

            <th>Originality</th>
            <th>Format</th>
            <th>Language</th>
            <th></th>
        </tr>
        </thead>

        <tbody>

        <?php foreach ($data as $review): ?>
            <?php if (!is_array($review)) break; ?>

            <tr>
                <td><a href="<?= ROOT_PATH.FILES.$review["title"]; ?>" target="_blank"><?= $review["title"]; ?></a></td>
                <td><?= $review["author"]; ?></td>
                <td><?= $review["date"]; ?></td>

                <td><?= $review["originality"] == null ? "" : $review["originality"]; ?></td>
                <td><?= $review["format"] == null ? "" : $review["format"]; ?></td>
                <td><?= $review["language"] == null ? "" : $review["language"]; ?></td>

                <td>
                    <div>
                        <?php if ($review["status"] == "reviewing"): ?>
                            <a href="<?= INDEX."?page=new_review&id_review=".$review["id_review"] ?>" class="btn btn-primary" role="button" aria-pressed="true">Review</a>
                        <?php else: ?>
                            <?php echo $review["status"] ?>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
</div>

<div class="row mb-5 mx-auto">
    <p class="col-4 ml-auto h5">Last login: <span class="h6"><?= $data["last_login"] ?></span></p>
</div>


<!--<form class="form-inline">-->
<!--    <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Preference</label>-->
<!--    <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">-->
<!--        <option selected>Choose...</option>-->
<!--        <option value="1">One</option>-->
<!--        <option value="2">Two</option>-->
<!--        <option value="3">Three</option>-->
<!--    </select>-->
<!---->
<!--    <div class="custom-control custom-checkbox my-1 mr-sm-2">-->
<!--        <input type="checkbox" class="custom-control-input" id="customControlInline">-->
<!--        <label class="custom-control-label" for="customControlInline">Remember my preference</label>-->
<!--    </div>-->
<!---->
<!--    <button type="submit" class="btn btn-primary my-1">Submit</button>-->
<!--</form>-->